application:
  host: 127.0.0.1
  port: 8081
  base_url: http://127.0.0.1
  hmac_secret: 8EFy1b9esARlwULtJV46XQp0OWqifNoG
database:
  username: postgres
  password: postgres
  port: 5432
  host: localhost
  database_name: newsletter
  require_ssl: false
email_client:
  base_url: 'https://api.postmarkapp.com'
  sender_email: 'ezreal_rao@zyinfo.tech'
  authorization_token: '31cc22d1-9318-4369-830c-aeb41b48f16f'
  timeout_milliseconds: 10000
